[pytest]
pythonpath = .
filterwarnings =
    ignore:.*Map is deprecated.*:DeprecationWarning
    ignore::DeprecationWarning:pyasn1.*
    ignore::sqlalchemy.exc.MovedIn20Warning:celery_sqlalchemy_scheduler.*
    ignore::sqlalchemy.exc.SAWarning:celery_sqlalchemy_scheduler.*








env_files = .env.test
