"""Add built_in and created_at to association tables

Revision ID: 00fddd07a659
Revises: a1702bd8d196
Create Date: 2025-11-16 17:24:13.126022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00fddd07a659'
down_revision: Union[str, Sequence[str], None] = 'a1702bd8d196'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_role_association', sa.Column('built_in', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('group_role_association', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('role_permission_association', sa.Column('built_in', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('role_permission_association', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('user_group_association', sa.Column('built_in', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('user_group_association', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_group_association', 'created_at')
    op.drop_column('user_group_association', 'built_in')
    op.drop_column('role_permission_association', 'created_at')
    op.drop_column('role_permission_association', 'built_in')
    op.drop_column('group_role_association', 'created_at')
    op.drop_column('group_role_association', 'built_in')
    # ### end Alembic commands ###
