"""Add built_in flag and remove is_admin

Revision ID: 0db178c366d2
Revises: edcf6dd062ee
Create Date: 2025-11-16 16:51:56.091435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0db178c366d2'
down_revision: Union[str, Sequence[str], None] = 'edcf6dd062ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('built_in', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('permissions', sa.Column('built_in', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('roles', sa.Column('built_in', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('users', sa.Column('built_in', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'built_in')
    op.drop_column('roles', 'built_in')
    op.drop_column('permissions', 'built_in')
    op.drop_column('groups', 'built_in')
    # ### end Alembic commands ###
