"""add_ldap_fields_to_user

Revision ID: 0ff50fc09db1
Revises: 68030afea72f
Create Date: 2026-01-17 10:36:38.300483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ff50fc09db1'
down_revision: Union[str, Sequence[str], None] = '68030afea72f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ldap_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('ldap_dn', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_ldap_id'), 'users', ['ldap_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_ldap_id'), table_name='users')
    op.drop_column('users', 'ldap_dn')
    op.drop_column('users', 'ldap_id')
    # ### end Alembic commands ###
