"""Refactor user model to use type instead of built_in and is_ldap

Revision ID: 1aa4bd2d1db4
Revises: f9627a56d88b
Create Date: 2026-01-03 21:04:17.298282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aa4bd2d1db4'
down_revision: Union[str, Sequence[str], None] = 'f9627a56d88b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Step 1: Add the new 'type' column, making it nullable for now
    op.add_column('users', sa.Column('type', sa.String(), nullable=True))

    # Step 2: Update the 'type' column based on the old 'built_in' and 'is_ldap' columns
    op.execute("UPDATE users SET type = 'built_in' WHERE built_in = TRUE")
    op.execute("UPDATE users SET type = 'ldap' WHERE is_ldap = TRUE AND built_in = FALSE")
    op.execute("UPDATE users SET type = 'local' WHERE type IS NULL")

    # Step 3: Now that all rows have a value, alter the column to be non-nullable
    op.alter_column('users', 'type', nullable=False)

    # Step 4: Drop the old columns
    op.drop_column('users', 'is_ldap')
    op.drop_column('users', 'built_in')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('built_in', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_ldap', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    
    # To reverse, we need to update the old columns based on the 'type'
    op.execute("UPDATE users SET built_in = TRUE WHERE type = 'built_in'")
    op.execute("UPDATE users SET is_ldap = TRUE WHERE type = 'ldap'")

    op.drop_column('users', 'type')
    # ### end Alembic commands ###
