"""add_task_secret_mapping

Revision ID: 258f588f89ea
Revises: 37ce5d843c50
Create Date: 2026-01-24 15:38:50.769799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '258f588f89ea'
down_revision: Union[str, Sequence[str], None] = '37ce5d843c50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_secret_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('setting_key', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_type', 'setting_key', name='unique_task_setting_mapping')
    )
    op.create_index(op.f('ix_task_secret_mappings_id'), 'task_secret_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_task_secret_mappings_task_type'), 'task_secret_mappings', ['task_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_secret_mappings_task_type'), table_name='task_secret_mappings')
    op.drop_index(op.f('ix_task_secret_mappings_id'), table_name='task_secret_mappings')
    op.drop_table('task_secret_mappings')
    # ### end Alembic commands ###
