"""add_trgm_indexes_to_user

Revision ID: 260df2ab4d3f
Revises: 258f588f89ea
Create Date: 2026-02-01 19:58:26.429966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '260df2ab4d3f'
down_revision: Union[str, Sequence[str], None] = '258f588f89ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.create_index('ix_users_login_trgm', 'users', ['login'], unique=False, postgresql_using='gin', postgresql_ops={'login': 'gin_trgm_ops'})
    op.create_index('ix_users_name_trgm', 'users', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_name_trgm', table_name='users', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index('ix_users_login_trgm', table_name='users', postgresql_using='gin', postgresql_ops={'login': 'gin_trgm_ops'})
    # ### end Alembic commands ###
