"""empty message

Revision ID: 3a210552adb2
Revises: 35e398cf6709
Create Date: 2025-10-04 23:20:34.690368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a210552adb2'
down_revision: Union[str, Sequence[str], None] = '35e398cf6709'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_acitve', sa.Boolean(), nullable=True))
    op.drop_column('users', 'is_acive')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_acive', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'is_acitve')
    # ### end Alembic commands ###
