"""Add core_settings and ldap_settings tables

Revision ID: 68030afea72f
Revises: 1aa4bd2d1db4
Create Date: 2026-01-11 00:50:00.720840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68030afea72f'
down_revision: Union[str, Sequence[str], None] = '1aa4bd2d1db4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_settings_id'), 'core_settings', ['id'], unique=False)
    op.create_index(op.f('ix_core_settings_key'), 'core_settings', ['key'], unique=True)
    op.create_table('ldap_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ldap_settings_id'), 'ldap_settings', ['id'], unique=False)
    op.create_index(op.f('ix_ldap_settings_key'), 'ldap_settings', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ldap_settings_key'), table_name='ldap_settings')
    op.drop_index(op.f('ix_ldap_settings_id'), table_name='ldap_settings')
    op.drop_table('ldap_settings')
    op.drop_index(op.f('ix_core_settings_key'), table_name='core_settings')
    op.drop_index(op.f('ix_core_settings_id'), table_name='core_settings')
    op.drop_table('core_settings')
    # ### end Alembic commands ###
